server:
  port: 8010
  servlet:
    context-path: /yokoto
spring:
  datasource:
    url: jdbc:mysql://localhost/yokotodb
    username: chris
    password: Chris@24
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
logging:
  level:
    '[org.hibernate.sql]': DEBUG
